---
title: "Data Cleaning"
author: "David Sutton"
date: "2/19/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(haven)
library(janitor)
library(rvest)
library(shiny)
library(broom)
library(gt)
options(scipen=999)
```

```{r, include = FALSE}

load("~/CCES.RData")

# First, copying the dataset.

CCES_Panel <- CCES_Panel_Full3waves_VV_V4
```

```{r, echo = FALSE}

# Cleaning data: First, isolating:

  # 2008-2012 Presidential switchers:

pres12 <- CCES_Panel %>%
  filter(CC10_317 < 3, CC12_410a < 3, CC10_317 != CC12_410a)

  # then, House of Rep 2010-2012;

house12 <- CCES_Panel %>%
  filter(CC10_412 < 3, CC12_412 < 3, CC10_412 != CC12_412)

  # then, House of Rep 2012-2014.

house14 <- CCES_Panel %>%
  filter(CC12_412 < 3, CC14_412 < 3, CC12_412 != CC14_412)

  # Now, writing code to drop variables we don't want/keep variables we want, filter
  # a couple variables, renaming the variables and creating an "Age" column for each
  # new dataset derived from the CCES.

house12_vars <- house12 %>%
  subset(select = c(caseid, birthyr_12, gender_12, race_12, CC10_412, CC12_412, CC12_302, CC12_303d, CC12_308a, CC12_308b, CC12_315a, CC12_320, CC12_321, CC12_322_1:CC12_322_6, CC12_324:CC12_329, CC12_341A, CC12_341C:CC12_341F, CC12_341M, CC12_350, CC12_367, CC12_387_1:CC12_387_13, CC12_418aa, CC12_422a:CC12_423bb, pid7_12, pid3_12, ideo5_12, pew_prayer_12, religpew_12, faminc_12, educ_12, StateAbbr_12)) %>%
  mutate("Age.12" = (2012 - birthyr_12))

house14_vars <- house14 %>%
  subset(select = c(caseid, birthyr_14, gender_14, race_14, CC12_412, CC14_412, CC14_302, CC14_303d, CC14_308a, CC14_308b, CC14_315a, CC14_320, CC14_321, CC14_322_1:CC14_322_6, CC14_324:CC14_329, CC14_341A, CC14_341C:CC14_341F, CC14_341M, CC14_350, CC14_367, CC14_387_1:CC14_387_13, CC14_418aa, CC14_422a:CC14_423bb, pid7_14, pid3_14, ideo5_14, pew_prayer_14, religpew_14, faminc_14, educ_14, StateAbbr_14)) %>%
  mutate("Age.14" = (2014 - birthyr_14))

pres12_vars <- pres12 %>%
  subset(select = c(caseid, birthyr_12, gender_12, race_12, CC10_317, CC12_410a, CC12_302, CC12_303d, CC12_308a, CC12_308b, CC12_315a, CC12_320, CC12_321, CC12_322_1:CC12_322_6, CC12_324:CC12_329, CC12_341A, CC12_341C:CC12_341F, CC12_341M, CC12_350, CC12_367, CC12_387_1:CC12_387_13, CC12_418aa, CC12_422a:CC12_423bb, pid7_12, pid3_12, ideo5_12, pew_prayer_12, religpew_12, faminc_12, educ_12, StateAbbr_12)) %>%
  mutate("pres.age.12" = (2012 - birthyr_12), pres.agegroup12 = case_when(pres.age.12 >= 18 & pres.age.12 <= 24 ~ '1', pres.age.12 >= 25 & pres.age.12 <= 34 ~ '2', pres.age.12 >= 35 & pres.age.12 <= 44 ~ '3', pres.age.12 >= 45 & pres.age.12 <= 54 ~ '4', pres.age.12 >= 55 & pres.age.12 <= 64 ~ '5', pres.age.12 >= 65 & pres.age.12 <= 74 ~ '6', pres.age.12 >= 75 & pres.age.12 <= 84 ~ '7', pres.age.12 >= 85 & pres.age.12 <= 94 ~ '8'))

  # Making variable numeric

pres12_vars$pres.agegroup12 <- as.numeric(pres12_vars$pres.agegroup12)

  # Renaming variables in new datasets.

house12_vars <- rename(house12_vars, housevote10 = CC10_412, housevote12 = CC12_412, economy12 = CC12_302, fedtax.retro12 = CC12_303d, obama.app12 = CC12_308a, congress.app12 = CC12_308b, guncontrol12 = CC12_320, climate12 = CC12_321, immg.status12 = CC12_322_1, immg.borderpatrol12 = CC12_322_2, immg.policeqs12 = CC12_322_3, immg.finebiz12 = CC12_322_4, immg.pubgoods12 = CC12_322_5, immg.citzdenial12 = CC12_322_6, abortion12 = CC12_324, jobs.envir12 = CC12_325, gaymarriage12 = CC12_326, affirmact12 = CC12_327, balbudget1.12 = CC12_328, balbudget2.12 = CC12_329, selfideo12 = CC12_341A, obamaideo12 = CC12_341C, romneyideo12 = CC12_341D, demideo12 = CC12_341E, repideo12 = CC12_341F, houserepideo12 = CC12_341M, partyreg12 = CC12_350, repHouserep12 = CC12_367, docvisit12 = CC12_387_1, newchild12 = CC12_387_10, moveoutchild12 = CC12_387_11, newmarriage12 = CC12_387_12, newdivorce12 = CC12_387_13, descriptrep.race.eth12 = CC12_418aa, AAraceresentA12 = CC12_422a, AAraceresentB12 = CC12_422b, Hispraceresent12 = CC12_423aa, state12 = StateAbbr_12)

house14_vars <- rename(house14_vars, housevote12 = CC12_412, housevote14 = CC14_412, economy14 = CC14_302, fedtax.retro14 = CC14_303d, obama.app14 = CC14_308a, congress.app14 = CC14_308b, guncontrol14 = CC14_320, climate14 = CC14_321, immg.status14 = CC14_322_1, immg.borderpatrol14 = CC14_322_2, immg.policeqs14 = CC14_322_3, immg.finebiz14 = CC14_322_4, immg.pubgoods14 = CC14_322_5, immg.citzdenial14 = CC14_322_6, abortion14 = CC14_324, jobs.envir14 = CC14_325, gaymarriage14 = CC14_326, affirmact14 = CC14_327, balbudget1.14 = CC14_328, balbudget2.14 = CC14_329, selfideo14 = CC14_341A, obamaideo14 = CC14_341C, demideo14 = CC14_341E, repideo14 = CC14_341F, houserepideo14 = CC14_341M, partyreg14 = CC14_350, repHouserep14 = CC14_367, docvisit14 = CC14_387_1, newchild14 = CC14_387_10, moveoutchild14 = CC14_387_11, newmarriage14 = CC14_387_12, newdivorce14 = CC14_387_13, descriptrep.race.eth14 = CC14_418aa, AAraceresentA14 = CC14_422a, AAraceresentB14 = CC14_422b, Hispraceresent14 = CC14_423aa, state14 = StateAbbr_14)

pres12_vars <- rename(pres12_vars, presvote08 = CC10_317, presvote12 = CC12_410a, economy12 = CC12_302, fedtax.retro12 = CC12_303d, obama.app12 = CC12_308a, congress.app12 = CC12_308b, guncontrol12 = CC12_320, climate12 = CC12_321, immg.status12 = CC12_322_1, immg.borderpatrol12 = CC12_322_2, immg.policeqs12 = CC12_322_3, immg.finebiz12 = CC12_322_4, immg.pubgoods12 = CC12_322_5, immg.citzdenial12 = CC12_322_6, abortion12 = CC12_324, jobs.envir12 = CC12_325, gaymarriage12 = CC12_326, affirmact12 = CC12_327, balbudget1.12 = CC12_328, balbudget2.12 = CC12_329, selfideo12 = CC12_341A, obamaideo12 = CC12_341C, romneyideo12 = CC12_341D, demideo12 = CC12_341E, repideo12 = CC12_341F, houserepideo12 = CC12_341M, partyreg12 = CC12_350, repHouserep12 = CC12_367, docvisit12 = CC12_387_1, newchild12 = CC12_387_10, moveoutchild12 = CC12_387_11, newmarriage12 = CC12_387_12, newdivorce12 = CC12_387_13, descriptrep.race.eth12 = CC12_418aa, AAraceresentA12 = CC12_422a, AAraceresentB12 = CC12_422b, Hispraceresent12 = CC12_423aa, state12 = StateAbbr_12)

  # Making one dataset with all House switchers

house.switch <- full_join(house12_vars, house14_vars, by = c("caseid", "housevote12"))

  # Now, one dataset of all switchers

switchers <- full_join(house.switch, pres12_vars, by = c("caseid", "birthyr_12", "gender_12", "race_12", "economy12", "fedtax.retro12", "obama.app12", "congress.app12", "CC12_315a", "guncontrol12", "climate12", "immg.status12", "immg.borderpatrol12", "immg.policeqs12", "immg.finebiz12", "immg.pubgoods12", "immg.citzdenial12", "abortion12", "jobs.envir12", "gaymarriage12", "affirmact12", "balbudget1.12", "balbudget2.12", "selfideo12", "obamaideo12", "CC12_341C_post", "romneyideo12", "CC12_341D_post", "demideo12", "CC12_341E_post", "repideo12", "houserepideo12", "partyreg12", "repHouserep12", "docvisit12", "newchild12", "moveoutchild12", "newmarriage12", "newdivorce12", "descriptrep.race.eth12", "AAraceresentA12", "AAraceresentB12", "CC12_423a", "CC12_423a_other", "Hispraceresent12", "CC12_423b", "CC12_423b_other", "CC12_423bb", "pid7_12", "pid3_12", "ideo5_12", "pew_prayer_12", "religpew_12", "faminc_12", "educ_12", "state12"))
```

```{r, echo = FALSE}

  # New variables added - agegroup.12, agegroup.14, pres.agegroup12, income.12,
# income.14, and 3 columns which indicates to which switcher groups observations
# belong, with 1 as yes and 0 as no.

switchers <- switchers %>%
  mutate(agegroup.12 = case_when(Age.12 >= 18 & Age.12 <= 24 ~ '1', Age.12 >= 25 & Age.12 <= 34 ~ '2', Age.12 >= 35 & Age.12 <= 44 ~ '3', Age.12 >= 45 & Age.12 <= 54 ~ '4', Age.12 >= 55 & Age.12 <= 64 ~ '5', Age.12 >= 65 & Age.12 <= 74 ~ '6', Age.12 >= 75 & Age.12 <= 84 ~ '7', Age.12 >= 85 & Age.12 <= 94 ~ '8'),
         agegroup.14 = case_when(Age.14 >= 18 & Age.14 <= 24 ~ '1', Age.14 >= 25 & Age.14 <= 34 ~ '2', Age.14 >= 35 & Age.14 <= 44 ~ '3', Age.14 >= 45 & Age.14 <= 54 ~ '4', Age.14 >= 55 & Age.14 <= 64 ~ '5', Age.14 >= 65 & Age.14 <= 74 ~ '6', Age.14 >= 75 & Age.14 <= 84 ~ '7', Age.14 >= 85 & Age.14 <= 94 ~ '8'),
         income.12 = case_when(faminc_12 >= 1 & faminc_12 <= 3 ~ '1', faminc_12 >= 4 & faminc_12 <= 6 ~ '2', faminc_12 >= 7 & faminc_12 <= 9 ~ '3', faminc_12 >= 10 & faminc_12 <= 11 ~ '4', faminc_12 >= 12 & faminc_12 < 33 ~ '5', faminc_12 >= 32 ~ '6'),
         income.14 = case_when(faminc_14 >= 1 & faminc_14 <= 3 ~ '1', faminc_14 >= 4 & faminc_14 <= 6 ~ '2', faminc_14 >= 7 & faminc_14 <= 9 ~ '3', faminc_14 >= 10 & faminc_14 <= 11 ~ '4', faminc_14 >= 12 & faminc_14 < 33 ~ '5', faminc_14 >= 32 ~ '6'),
         h12switch = if_else(housevote10 < 3 & housevote12 < 3 & housevote10 != housevote12, 1, 0),
         h14switch = if_else(housevote12 < 3 & housevote14 < 3 & housevote12 != housevote14, 1, 0),
         p12switch = if_else(presvote08 < 3 & presvote12 < 3 & presvote08 != presvote12, 1, 0))

  # Making variables numeric

switchers$agegroup.12 <- as.numeric(switchers$agegroup.12)

switchers$agegroup.14 <- as.numeric(switchers$agegroup.14)

switchers$pres.agegroup12 <- as.numeric(switchers$pres.agegroup12)

switchers$income.12 <- as.numeric(switchers$income.12)

switchers$income.14 <- as.numeric(switchers$income.14)
```

```{r, echo = FALSE}

# Who are these switchers? 

  # Demographics:
    
    # By race (percentages, dodged):

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(race_12, ..prop.., fill = reorder(presvote12, race_12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Race of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Race") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7), label = c("White", "Black", "Hispanic", "Asian", "Native American", "Mixed", "Other")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

      # or (percentages, stacked)

s1 <- switchers %>%
  filter(p12switch == 1) %>%
ggplot(aes(race_12, ..prop.., fill = reorder(presvote12, race_12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Race of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Race") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7), label = c("White", "Black", "Hispanic", "Asian", "Native American", "Mixed", "Other")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

    # By sex

s2 <- switchers %>%
  filter(p12switch == 1) %>%
ggplot(aes(gender_12, ..prop.., fill = reorder(presvote12, gender_12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Gender of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Gender") + scale_x_continuous(breaks = c(1, 2), label = c("Male", "Female")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Romney", "Obama"), values=c("red", "blue"))

  # By age

s3 <- switchers %>%
  filter(p12switch == 1) %>%
ggplot(aes(pres.agegroup12, ..prop.., fill = reorder(presvote12, pres.agegroup12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + xlab("Age of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Age") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8), label = c("18-24", "25-34", "35-44", "45-54", "55-64", "65-74", "75-84", "85-94")) + scale_y_continuous(labels = scales::percent) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Romney", "Obama"), values=c("red", "blue"))

    # By education

s4 <- switchers %>%
  filter(p12switch == 1) %>%
ggplot(aes(educ_12, ..prop.., fill = reorder(presvote12, educ_12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Education Level") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Education") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6), label = c("No High School", "High school graduate", "Some college", "2-year", "4-year", "Post-grad")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Romney", "Obama"), values=c("red", "blue")) + coord_flip()

    # By party (dropping NAs means 2 less observations)

s5 <- switchers %>%
  filter(p12switch == 1, partyreg12 < 5) %>%
  ggplot(aes(partyreg12, ..prop.., fill = reorder(presvote12, partyreg12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Party of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Party") + scale_x_continuous(breaks = c(1, 2, 3, 4), label = c("None/Ind/Didn't Say", "Democratic", "Republican", "Other")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Romney", "Obama"), values=c("red", "blue"))

    # By income

s6 <- switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(income.12, ..prop.., fill = reorder(presvote12, income.12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Income of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Income") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6), label = c("0-29,999", "30,000-59,999", "60,000-99,999", "100,000-149,999", "150,000+", "Didn't say/Skipped/Not asked")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue")) + coord_flip()
```

```{r, echo = FALSE}

# Comparing switchers to voters in general
  # Keeping only the variables we want and adding new variables to indicate
# switchers, make age groups and income groups

CCES_Panel <- CCES_Panel %>%
  subset(select = c(caseid, birthyr_12, birthyr_14, gender_12, gender_14, race_12,
                    race_14, CC10_317, CC12_410a, CC10_412, CC12_412, CC14_412,
                    CC12_302, CC14_302, CC12_303d, CC14_303d, CC12_308a, CC14_308a,
                    CC12_308b, CC14_308b, CC12_315a, CC14_315a, CC12_320, CC14_320,
                    CC12_321, CC14_321, CC12_322_1:CC12_322_6, CC14_322_1:CC14_322_6,
                    CC12_324:CC12_329, CC14_324:CC14_329, CC12_341A, CC14_341A,
                    CC12_341C:CC12_341F, CC14_341C:CC14_341F, CC12_341M, CC14_341M,
                    CC12_350, CC14_350, CC12_367, CC14_367, CC12_387_1:CC12_387_13,
                    CC14_387_1:CC14_387_13, CC12_418aa, CC14_418aa, CC12_422a:CC12_423bb,
                    CC14_422a:CC14_423bb, pid7_12, pid7_14, pid3_12, pid3_14, ideo5_12,
                    ideo5_14, pew_prayer_12, pew_prayer_14, religpew_12, religpew_14,
                    faminc_10, faminc_12, faminc_14, educ_12, educ_14, StateAbbr_12,
                    StateAbbr_14)) %>%
  rename(hvote10 = CC10_412, hvote12 = CC12_412, hvote14 = CC14_412,
       pvote08 = CC10_317, pvote12 = CC12_410a, partyreg12 = CC12_350) %>%
  mutate(h12switch = if_else(hvote10 < 3 & hvote12 < 3 & hvote10 != hvote12, 1, 0),
         h14switch = if_else(hvote12 < 3 & hvote14 < 3 & hvote12 != hvote14, 1, 0),
         p12switch = if_else(pvote08 < 3 & pvote12 < 3 & pvote08 != pvote12, 1, 0),
         age12 = (2012 - birthyr_12),
         age14 = (2014 - birthyr_14),
         agegroup12 = case_when(age12 >= 18 & age12 <= 24 ~ '1', age12 >= 25 & age12 <= 34 ~ '2',
                                age12 >= 35 & age12 <= 44 ~ '3', age12 >= 45 & age12 <= 54 ~ '4',
                                age12 >= 55 & age12 <= 64 ~ '5', age12 >= 65 & age12 <= 74 ~ '6',
                                age12 >= 75 & age12 <= 84 ~ '7', age12 >= 85 & age12 <= 94 ~ '8'),
         agegroup14 = case_when(age14 >= 18 & age14 <= 24 ~ '1', age14 >= 25 & age14 <= 34 ~ '2',
                                age14 >= 35 & age14 <= 44 ~ '3', age14 >= 45 & age14 <= 54 ~ '4',
                                age14 >= 55 & age14 <= 64 ~ '5', age14 >= 65 & age14 <= 74 ~ '6',
                                age14 >= 75 & age14 <= 84 ~ '7', age14 >= 85 & age14 <= 94 ~ '8'),
         income10 = case_when(faminc_10 >= 1 & faminc_10 <= 3 ~ '1', faminc_10 >= 4 & faminc_10 <= 6 ~ '2',
                              faminc_10 >= 7 & faminc_10 <= 9 ~ '3', faminc_10 >= 10 & faminc_10 <= 11 ~ '4',
                              faminc_10 >= 12 & faminc_10 < 33 ~ '5', faminc_10 >= 32 ~ '6'),
         income12 = case_when(faminc_12 >= 1 & faminc_12 <= 3 ~ '1', faminc_12 >= 4 & faminc_12 <= 6 ~ '2',
                              faminc_12 >= 7 & faminc_12 <= 9 ~ '3', faminc_12 >= 10 & faminc_12 <= 11 ~ '4',
                              faminc_12 >= 12 & faminc_12 < 33 ~ '5', faminc_12 >= 32 ~ '6'),
         income14 = case_when(faminc_14 >= 1 & faminc_14 <= 3 ~ '1', faminc_14 >= 4 & faminc_14 <= 6 ~ '2',
                              faminc_14 >= 7 & faminc_14 <= 9 ~ '3', faminc_14 >= 10 & faminc_14 <= 11 ~ '4',
                              faminc_14 >= 12 & faminc_14 < 33 ~ '5', faminc_14 >= 32 ~ '6'))

# How switchers compare to the electorate by
  # race:

CCES_Panel %>%
  group_by(p12switch) %>%
  count(race_12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(race_12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Race", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7), label = c("White", "Black", "Hispanic",
                                                                "Asian", "Native American",
                                                                "Mixed", "Other")) +
  theme_classic() +
  scale_fill_manual("Group", labels = c("Electorate", "Switchers"), values=c("dark green", "orange"))

  # gender:

CCES_Panel %>%
  group_by(p12switch) %>%
  count(gender_12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(gender_12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Gender", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_continuous(breaks = c(1, 2), label = c("Male", "Female")) +
  theme_classic() +
  scale_fill_manual("Group", labels = c("Electorate", "Switchers"), values=c("dark green", "orange"))

  # age:

CCES_Panel %>%
  group_by(p12switch) %>%
  count(agegroup12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(agegroup12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Age", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_discrete(breaks = c(1, 2, 3, 4, 5, 6, 7, 8), label = c("18-24", "25-34", "35-44",
                                                                   "45-54", "55-64", "65-74", "75-84",
                                                                   "85-94")) +
  theme_classic() +
  scale_fill_manual("Group", labels = c("Electorate", "Switchers"), values=c("dark green", "orange"))

  # education:

CCES_Panel %>%
  group_by(p12switch) %>%
  count(educ_12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(educ_12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Education", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6), label = c("No High School",
                                                           "High school graduate", "Some college",
                                                           "2-year", "4-year", "Post-grad")) +
  theme_classic() +
  scale_fill_manual("Group", labels = c("Electorate", "Switchers"), values=c("dark green", "orange")) +
  coord_flip()

  # party

CCES_Panel %>%
  filter(partyreg12 < 5) %>%
  group_by(p12switch) %>%
  count(partyreg12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(partyreg12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Party", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_continuous(breaks = c(1, 2, 3, 4), label = c("None/Independent/Didn't Say",
                                                           "Democrat", "Republican",
                                                           "Other")) +
  theme_classic() +
  scale_fill_manual("Group", labels = c("Electorate", "Switchers"), values=c("dark green", "orange"))

  # income
  
CCES_Panel %>%
  group_by(p12switch) %>%
  count(income12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(income12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Income", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_discrete(breaks = c(1, 2, 3, 4, 5, 6), label = c("0-29,999", "30,000-59,999",
                                                             "60,000-99,999", "100,000-149,999",
                                                             "150,000+", "Didn't say/Skipped/Not asked")) +
  theme_classic() +
  scale_fill_manual("Group", labels = c("Electorate", "Switchers"), values=c("dark green", "orange")) +
  coord_flip()
```

```{r, echo = FALSE}

# regression exploration on race and pres. 2012 switching

pres12.race <- CCES_Panel %>%
  mutate(race_12 = ifelse(is.na(race_12), 0, race_12),
         p12switch = ifelse(is.na(p12switch), 0, p12switch),
         white = ifelse(race_12 == 1, 1, 0),
         black = ifelse(race_12 == 2, 1, 0),
         hispanic = ifelse(race_12 == 3, 1, 0),
         asian = ifelse(race_12 == 4, 1, 0),
         native.american = ifelse(race_12 == 5, 1, 0),
         mixed = ifelse(race_12 == 6, 1, 0),
         other = ifelse(race_12 == 7, 1, 0),
         middle.eastern = ifelse(race_12 == 8, 1, 0)) %>%
  select(p12switch, white, black, hispanic, asian, native.american, mixed, other, middle.eastern)

pres12.race.model <- glm(p12switch ~ white + black + hispanic + asian, binomial, pres12.race) %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, conf.low, conf.high) %>%
  print()
```

```{r, echo = FALSE}

# some plots

# 2008 voters on racial attitudes towards Blacks and Hispanics, by vote for president

CCES_Panel_Full3waves_VV_V4 %>%
  filter(CC12_317 < 3, CC12_422a < 6) %>%
  ggplot(aes(CC12_422a)) + geom_bar(aes(y = (..count..)/sum(..count..))) + geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = -.5) + xlab("Response") + ylab("Portion") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5), label = c("Strongly agree", "Somewhat agree", "Neither agree nor disagree", "Somewhat disagree", "Strongly disagree")) + ggtitle("Racial Resentment of Blacks - 1", subtitle = "The Irish, Italians, Jews and many other minorities overcame prejudice and worked their way up.\nBlacks should do the same without any special favors.") + theme(axis.text.x = element_text(hjust = 1, angle = 30)) + facet_wrap(~ CC12_317, labeller = labeller(CC12_317 = c("1" = "'08 Obama Voters", "2" = "'08 McCain Voters")))

CCES_Panel_Full3waves_VV_V4 %>%
  filter(CC12_317 < 3, CC12_422b < 6) %>%
  ggplot(aes(CC12_422b)) + geom_bar(aes(y = (..count..)/sum(..count..))) + geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = -.5) + xlab("Response") + ylab("Portion") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5), label = c("Strongly agree", "Somewhat agree", "Neither agree nor disagree", "Somewhat disagree", "Strongly disagree")) + ggtitle("Racial Resentment of Blacks - 2", subtitle = "Generations of slavery and discrimination have created conditions that make it difficult for Blacks\nto work their way out of the lower class.") + theme(axis.text.x = element_text(hjust = 1, angle = 30)) + facet_wrap(~ CC12_317, labeller = labeller(CC12_317 = c("1" = "'08 Obama Voters", "2" = "'08 McCain Voters")))

CCES_Panel_Full3waves_VV_V4 %>%
  filter(CC12_317 < 3, CC12_423aa < 6) %>%
  ggplot(aes(CC12_423aa)) + geom_bar(aes(y = (..count..)/sum(..count..))) + geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = -.5) + xlab("Response") + ylab("Portion") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5), label = c("Strongly agree", "Somewhat agree", "Neither agree nor disagree", "Somewhat disagree", "Strongly disagree")) + ggtitle("Racial Resentment of Hispanics - 1", subtitle = "The Irish, Italians, Jews and many other minorities overcame prejudice and worked their way up.\nHispanics should do the same without any special favors.") + theme(axis.text.x = element_text(hjust = 1, angle = 30)) + facet_wrap(~ CC12_317, labeller = labeller(CC12_317 = c("1" = "'08 Obama Voters", "2" = "'08 McCain Voters")))

CCES_Panel_Full3waves_VV_V4 %>%
  filter(CC12_317 < 3, CC12_423bb < 6) %>%
  ggplot(aes(CC12_423bb)) + geom_bar(aes(y = (..count..)/sum(..count..))) + geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = -.5) + xlab("Response") + ylab("Portion") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5), label = c("Strongly agree", "Somewhat agree", "Neither agree nor disagree", "Somewhat disagree", "Strongly disagree")) + ggtitle("Racial Resentment of Hispanics - 2", subtitle = "Generations of slavery and discrimination have created conditions that make it difficult for\nHispanics to work their way out of the lower class.") + theme(axis.text.x = element_text(hjust = 1, angle = 30)) + facet_wrap(~ CC12_317, labeller = labeller(CC12_317 = c("1" = "'08 Obama Voters", "2" = "'08 McCain Voters")))

# Change in Presidential Approval in general public vs changes in presidential approval in switchers

CCES_Panel_Full3waves_VV_V4 %>%
  filter(CC10_308a < 5, CC12_308a < 5, CC14_308a < 5) %>%
  ggplot(aes(as.numeric(CC10_308a - CC14_308a))) + geom_bar() + geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = 1) + xlab("<-Negative Movement Positive->") + ylab("Respondents") + ggtitle("Change in Presidential Approval from 2010 to 2014: General Public")

# Change in presidential approval in switchers

CCES_Panel_Full3waves_VV_V4 %>%
  filter(CC10_308a < 5, CC12_308a < 5, CC14_308a < 5, CC10_317 < 3, CC12_410a < 3, CC10_317 != CC12_410a) %>%
  ggplot(aes(as.numeric(CC10_308a - CC14_308a))) + geom_bar() + geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = 1) + xlab("<-Negative Movement Positive->") + ylab("Respondents") + ggtitle("Change in Presidential Approval from 2010 to 2014: Switchers")

# Change in presidential approval for D-to-R switchers

CCES_Panel_Full3waves_VV_V4 %>%
  filter(CC10_308a < 5, CC12_308a < 5, CC14_308a < 5, CC10_317 == 1, CC12_410a == 2) %>%
  ggplot(aes(as.numeric(CC10_308a - CC14_308a))) + geom_bar() + geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = 1) + xlab("<-Negative Movement Positive->") + ylab("Respondents") + ggtitle("Change in Presidential Approval from 2010 to 2014: Dem-to-Rep Switchers")

# Change in presidential approval for R-to-D switchers

CCES_Panel_Full3waves_VV_V4 %>%
  filter(CC10_308a < 5, CC12_308a < 5, CC14_308a < 5, CC10_317 == 2, CC12_410a == 1) %>%
  ggplot(aes(as.numeric(CC10_308a - CC14_308a))) + geom_bar() + geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = 1) + xlab("<-Negative Movement Positive->") + ylab("Respondents") + ggtitle("Change in Presidential Approval from 2010 to 2014: Rep-to-Dem Switchers")
```
