---
title: "Data Cleaning"
author: "David Sutton"
date: "2/19/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(haven)
library(janitor)
library(rvest)
library(shiny)
library(broom)
library(gt)
library(skimr)
library(rpart)
library(tidymodels)
library(rpart.plot)
library(parsnip)
library(fastDummies)
library(fivethirtyeight)
options(scipen=999)
```

```{r initial loading and copying, include = FALSE}

# The dataset - 2010-2014 Cooperative Congressional Election Study Panel Survey

load("~/CCES.RData")

# Copying the dataset.

CCES_Panel <- CCES_Panel_Full3waves_VV_V4
```

```{r cleanig and isolating groups, echo = FALSE}

# Cleaning data: First, isolating:

  # 2008-2012 Presidential switchers:

pres12 <- CCES_Panel %>%
  filter(CC10_317 < 3, CC12_410a < 3, CC10_317 != CC12_410a)

  # then, House of Rep 2010-2012;

house12 <- CCES_Panel %>%
  filter(CC10_412 < 3, CC12_412 < 3, CC10_412 != CC12_412)

  # then, House of Rep 2012-2014.

house14 <- CCES_Panel %>%
  filter(CC12_412 < 3, CC14_412 < 3, CC12_412 != CC14_412)

  # Now, writing code to drop variables we don't want/keep variables we want, filter
  # a couple variables, renaming the variables and creating an "Age" column for each
  # new dataset derived from the CCES.

house12_vars <- house12 %>%
  subset(select = c(caseid, birthyr_12, gender_12, race_12, CC10_412, CC12_412, CC12_302, CC12_303d, CC12_308a, CC12_308b, CC12_315a, CC12_320, CC12_321, CC12_322_1:CC12_322_6, CC12_324:CC12_329, CC12_341A, CC12_341C:CC12_341F, CC12_341M, CC12_350, CC12_367, CC12_387_1:CC12_387_13, CC12_418aa, CC12_422a:CC12_423bb, pid7_12, pid3_12, ideo5_12, pew_prayer_12, religpew_12, faminc_12, educ_12, StateAbbr_12)) %>%
  mutate("Age.12" = (2012 - birthyr_12))

house14_vars <- house14 %>%
  subset(select = c(caseid, birthyr_14, gender_14, race_14, CC12_412, CC14_412, CC14_302, CC14_303d, CC14_308a, CC14_308b, CC14_315a, CC14_320, CC14_321, CC14_322_1:CC14_322_6, CC14_324:CC14_329, CC14_341A, CC14_341C:CC14_341F, CC14_341M, CC14_350, CC14_367, CC14_387_1:CC14_387_13, CC14_418aa, CC14_422a:CC14_423bb, pid7_14, pid3_14, ideo5_14, pew_prayer_14, religpew_14, faminc_14, educ_14, StateAbbr_14)) %>%
  mutate("Age.14" = (2014 - birthyr_14))

pres12_vars <- pres12 %>%
  subset(select = c(caseid, birthyr_12, gender_12, race_12, CC10_317, CC12_410a, CC12_302, CC12_303d, CC12_308a, CC12_308b, CC12_315a, CC12_320, CC12_321, CC12_322_1:CC12_322_6, CC12_324:CC12_329, CC12_341A, CC12_341C:CC12_341F, CC12_341M, CC12_350, CC12_367, CC12_387_1, CC12_387_2, CC12_387_3, CC12_387_4, CC12_387_5, CC12_387_6, CC12_387_7, CC12_387_8, CC12_387_9, CC12_387_10, CC12_387_11, CC12_387_12, CC12_387_13, CC12_418aa, CC12_422a:CC12_423bb, pid7_12, pid3_12, ideo5_12, pew_prayer_12, religpew_12, faminc_12, educ_12, StateAbbr_12)) %>%
  mutate("pres.age.12" = (2012 - birthyr_12), pres.agegroup12 = case_when(pres.age.12 >= 18 & pres.age.12 <= 24 ~ '1', pres.age.12 >= 25 & pres.age.12 <= 34 ~ '2', pres.age.12 >= 35 & pres.age.12 <= 44 ~ '3', pres.age.12 >= 45 & pres.age.12 <= 54 ~ '4', pres.age.12 >= 55 & pres.age.12 <= 64 ~ '5', pres.age.12 >= 65 & pres.age.12 <= 74 ~ '6', pres.age.12 >= 75 & pres.age.12 <= 84 ~ '7', pres.age.12 >= 85 & pres.age.12 <= 94 ~ '8')) 

  # Making variable numeric

pres12_vars$pres.agegroup12 <- as.numeric(pres12_vars$pres.agegroup12)

  # Renaming variables in new datasets.

house12_vars <- rename(house12_vars, housevote10 = CC10_412, housevote12 = CC12_412, economy12 = CC12_302, fedtax.retro12 = CC12_303d, obama.app12 = CC12_308a, congress.app12 = CC12_308b, guncontrol12 = CC12_320, climate12 = CC12_321, immg.status12 = CC12_322_1, immg.borderpatrol12 = CC12_322_2, immg.policeqs12 = CC12_322_3, immg.finebiz12 = CC12_322_4, immg.pubgoods12 = CC12_322_5, immg.citzdenial12 = CC12_322_6, abortion12 = CC12_324, jobs.envir12 = CC12_325, gaymarriage12 = CC12_326, affirmact12 = CC12_327, balbudget1.12 = CC12_328, balbudget2.12 = CC12_329, selfideo12 = CC12_341A, obamaideo12 = CC12_341C, romneyideo12 = CC12_341D, demideo12 = CC12_341E, repideo12 = CC12_341F, houserepideo12 = CC12_341M, partyreg12 = CC12_350, repHouserep12 = CC12_367, docvisit12 = CC12_387_1, newchild12 = CC12_387_10, moveoutchild12 = CC12_387_11, newmarriage12 = CC12_387_12, newdivorce12 = CC12_387_13, descriptrep.race.eth12 = CC12_418aa, AAraceresentA12 = CC12_422a, AAraceresentB12 = CC12_422b, Hispraceresent12 = CC12_423aa, state12 = StateAbbr_12)

house14_vars <- rename(house14_vars, housevote12 = CC12_412, housevote14 = CC14_412, economy14 = CC14_302, fedtax.retro14 = CC14_303d, obama.app14 = CC14_308a, congress.app14 = CC14_308b, guncontrol14 = CC14_320, climate14 = CC14_321, immg.status14 = CC14_322_1, immg.borderpatrol14 = CC14_322_2, immg.policeqs14 = CC14_322_3, immg.finebiz14 = CC14_322_4, immg.pubgoods14 = CC14_322_5, immg.citzdenial14 = CC14_322_6, abortion14 = CC14_324, jobs.envir14 = CC14_325, gaymarriage14 = CC14_326, affirmact14 = CC14_327, balbudget1.14 = CC14_328, balbudget2.14 = CC14_329, selfideo14 = CC14_341A, obamaideo14 = CC14_341C, demideo14 = CC14_341E, repideo14 = CC14_341F, houserepideo14 = CC14_341M, partyreg14 = CC14_350, repHouserep14 = CC14_367, docvisit14 = CC14_387_1, newchild14 = CC14_387_10, moveoutchild14 = CC14_387_11, newmarriage14 = CC14_387_12, newdivorce14 = CC14_387_13, descriptrep.race.eth14 = CC14_418aa, AAraceresentA14 = CC14_422a, AAraceresentB14 = CC14_422b, Hispraceresent14 = CC14_423aa, state14 = StateAbbr_14)

pres12_vars <- rename(pres12_vars, presvote08 = CC10_317, presvote12 = CC12_410a, economy12 = CC12_302, fedtax.retro12 = CC12_303d, obama.app12 = CC12_308a, congress.app12 = CC12_308b, guncontrol12 = CC12_320, climate12 = CC12_321, immg.status12 = CC12_322_1, immg.borderpatrol12 = CC12_322_2, immg.policeqs12 = CC12_322_3, immg.finebiz12 = CC12_322_4, immg.pubgoods12 = CC12_322_5, immg.citzdenial12 = CC12_322_6, abortion12 = CC12_324, jobs.envir12 = CC12_325, gaymarriage12 = CC12_326, affirmact12 = CC12_327, balbudget1.12 = CC12_328, balbudget2.12 = CC12_329, selfideo12 = CC12_341A, obamaideo12 = CC12_341C, romneyideo12 = CC12_341D, demideo12 = CC12_341E, repideo12 = CC12_341F, houserepideo12 = CC12_341M, partyreg12 = CC12_350, repHouserep12 = CC12_367, docvisit12 = CC12_387_1, eroom12 = CC12_387_2, raise12 = CC12_387_3, lostjob12 = CC12_387_4, cutbenefits12 = CC12_387_5, promotion12 = CC12_387_6, betterjob12 = CC12_387_7, trafficticket12 = CC12_387_8, crimevic12 = CC12_387_9, newchild12 = CC12_387_10, moveoutchild12 = CC12_387_11, newmarriage12 = CC12_387_12, newdivorce12 = CC12_387_13, descriptrep.race.eth12 = CC12_418aa, AAraceresentA12 = CC12_422a, AAraceresentB12 = CC12_422b, Hispraceresent12 = CC12_423aa, state12 = StateAbbr_12)

  # Making one dataset with all House switchers

house.switch <- full_join(house12_vars, house14_vars, by = c("caseid", "housevote12"))

  # Now, one dataset of all switchers

switchers <- full_join(house.switch, pres12_vars, by = c("caseid", "birthyr_12", "gender_12", "race_12", "economy12", "fedtax.retro12", "obama.app12", "congress.app12", "CC12_315a", "guncontrol12", "climate12", "immg.status12", "immg.borderpatrol12", "immg.policeqs12", "immg.finebiz12", "immg.pubgoods12", "immg.citzdenial12", "abortion12", "jobs.envir12", "gaymarriage12", "affirmact12", "balbudget1.12", "balbudget2.12", "selfideo12", "obamaideo12", "CC12_341C_post", "romneyideo12", "CC12_341D_post", "demideo12", "CC12_341E_post", "repideo12", "houserepideo12", "partyreg12", "repHouserep12", "docvisit12", "newchild12", "moveoutchild12", "newmarriage12", "newdivorce12", "descriptrep.race.eth12", "AAraceresentA12", "AAraceresentB12", "CC12_423a", "CC12_423a_other", "Hispraceresent12", "CC12_423b", "CC12_423b_other", "CC12_423bb", "pid7_12", "pid3_12", "ideo5_12", "pew_prayer_12", "religpew_12", "faminc_12", "educ_12", "state12"))
```

```{r making switchers dataset more workable, echo = FALSE}

  # New variables added - agegroup.12, agegroup.14, pres.agegroup12, income.12,
# income.14, and 3 columns which indicates to which switcher groups observations
# belong, with 1 as yes and 0 as no.

switchers <- switchers %>%
  mutate(agegroup.12 = case_when(Age.12 >= 18 & Age.12 <= 24 ~ '1', Age.12 >= 25 & Age.12 <= 34 ~ '2', Age.12 >= 35 & Age.12 <= 44 ~ '3', Age.12 >= 45 & Age.12 <= 54 ~ '4', Age.12 >= 55 & Age.12 <= 64 ~ '5', Age.12 >= 65 & Age.12 <= 74 ~ '6', Age.12 >= 75 & Age.12 <= 84 ~ '7', Age.12 >= 85 & Age.12 <= 94 ~ '8'),
         agegroup.14 = case_when(Age.14 >= 18 & Age.14 <= 24 ~ '1', Age.14 >= 25 & Age.14 <= 34 ~ '2', Age.14 >= 35 & Age.14 <= 44 ~ '3', Age.14 >= 45 & Age.14 <= 54 ~ '4', Age.14 >= 55 & Age.14 <= 64 ~ '5', Age.14 >= 65 & Age.14 <= 74 ~ '6', Age.14 >= 75 & Age.14 <= 84 ~ '7', Age.14 >= 85 & Age.14 <= 94 ~ '8'),
         income.12 = case_when(faminc_12 >= 1 & faminc_12 <= 3 ~ '1', faminc_12 >= 4 & faminc_12 <= 6 ~ '2', faminc_12 >= 7 & faminc_12 <= 9 ~ '3', faminc_12 >= 10 & faminc_12 <= 11 ~ '4', faminc_12 >= 12 & faminc_12 < 33 ~ '5', faminc_12 >= 32 | is.na(faminc_12) ~ '6'),
         income.14 = case_when(faminc_14 >= 1 & faminc_14 <= 3 ~ '1', faminc_14 >= 4 & faminc_14 <= 6 ~ '2', faminc_14 >= 7 & faminc_14 <= 9 ~ '3', faminc_14 >= 10 & faminc_14 <= 11 ~ '4', faminc_14 >= 12 & faminc_14 < 33 ~ '5', faminc_14 >= 32 | is.na(faminc_14) ~ '6'),
         h12switch = if_else(housevote10 < 3 & housevote12 < 3 & housevote10 != housevote12, 1, 0),
         h14switch = if_else(housevote12 < 3 & housevote14 < 3 & housevote12 != housevote14, 1, 0),
         p12switch = if_else(presvote08 < 3 & presvote12 < 3 & presvote08 != presvote12, 1, 0))

  # Making variables numeric

switchers$agegroup.12 <- as.numeric(switchers$agegroup.12)

switchers$agegroup.14 <- as.numeric(switchers$agegroup.14)

switchers$pres.agegroup12 <- as.numeric(switchers$pres.agegroup12)

switchers$income.12 <- as.numeric(switchers$income.12)

switchers$income.14 <- as.numeric(switchers$income.14)
```

```{r policy and public opinion plots for switchers, echo = FALSE}

# economy

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(economy12, ..prop.., fill = reorder(presvote12, economy12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Economy", subtitle = "Switchers voted for the incumbent despite their opinion on the economy") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6), label = c("Gotten much better", "Gotten better", "Stayed about the same", "Gotten Worse", "Gotten much worse", "Not sure")) + theme_classic() + scale_fill_manual("Voted for", labels = c("McCain-Obama", "Obama-Romney"), values=c("blue", "red"))

# taxes

switchers %>%
  filter(p12switch == 1, fedtax.retro12 < 5) %>% # fedtax filter gets rid of  NAs
  ggplot(aes(fedtax.retro12, ..prop.., fill = reorder(presvote12, fedtax.retro12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Taxes Paid") + scale_x_continuous(breaks = c(1, 2, 3, 4), label = c("Increased", "Decreased", "Stayed the same","Not sure")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

# gun control

switchers %>%
  filter(p12switch == 1, guncontrol12 < 4) %>% # guncontrol filter leaves out NAs
  ggplot(aes(guncontrol12, ..prop.., fill = reorder(presvote12, guncontrol12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Gun Control") + scale_x_continuous(breaks = c(1, 2, 3), label = c("More Strict", "Less Strict", "Kept As They Are")) + theme_classic() + scale_fill_manual("Voted for", labels = c("McCain-Obama", "Obama-Romney"), values=c("blue", "red"))

# immigration - legal status
switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(immg.status12, ..prop.., fill = reorder(presvote12, immg.status12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Immigration") + scale_x_continuous(breaks = c(1, 2), label = c("Yes", "No")) + theme_classic() + scale_fill_manual("Voted for", labels = c("McCain-Obama", "Obama-Romney"), values=c("blue", "red"))

# immigration - border patrol

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(immg.borderpatrol12, ..prop.., fill = reorder(presvote12, immg.borderpatrol12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Immigration") + scale_x_continuous(breaks = c(1, 2), label = c("Yes", "No")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

# immigration - police questioning

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(immg.policeqs12, ..prop.., fill = reorder(presvote12, immg.policeqs12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Immigration") + scale_x_continuous(breaks = c(1, 2), label = c("Yes", "No")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

# immigration - fine American businesses

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(immg.finebiz12, ..prop.., fill = reorder(presvote12, immg.finebiz12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Immigration") + scale_x_continuous(breaks = c(1, 2), label = c("Yes", "No")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

# immigration - use public goods

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(immg.pubgoods12, ..prop.., fill = reorder(presvote12, immg.pubgoods12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Immigration") + scale_x_continuous(breaks = c(1, 2), label = c("Yes", "No")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

# immigration - deny citizenship

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(immg.citzdenial12, ..prop.., fill = reorder(presvote12, immg.citzdenial12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Immigration") + scale_x_continuous(breaks = c(1, 2), label = c("Yes", "No")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

# abortion

switchers %>%
  filter(p12switch == 1, abortion12 < 5) %>% # abortion filter drops NAs
  ggplot(aes(abortion12, ..prop.., fill = reorder(presvote12, abortion12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + xlab("Opinion") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Opinion on Immigration") + scale_x_continuous(breaks = c(1, 2, 3, 4), label = c("By law, abortion should never be permitted", "The law should permit abortion only in case of rape, incest or when the woman's life is in danger", "The law should permit abortion for reasons other than rape, incest, or danger to the woman's life, but only after the need for the abortion has been clearly established", "By law, a woman should always be able to obtain an abortion as a matter of personal choice")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

# gay marriage

switchers %>%
  filter(p12switch == 1, gaymarriage12 < 3) %>% # gay marriage filter drops NAs
  ggplot(aes(gaymarriage12, ..prop.., fill = reorder(presvote12, gaymarriage12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + labs(title = "President 2012 Switchers by Opinion on Gay Marriage", x = "Opinion", y = "Percentage of Switchers") + scale_x_continuous(breaks = c(1, 2), label = c("Yes", "No")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

# affirmative action

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(affirmact12, ..prop.., fill = reorder(presvote12, affirmact12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + labs(title = "President 2012 Switchers by Opinion on Affirmative Action", x = "Opinion", y = "Percentage of Switchers") + scale_x_continuous(breaks = c(1, 2, 3, 4), label = c("Strongly support", "Somewhat support", "Somewhat oppose", "Strongly oppose")) + theme_classic() + scale_fill_manual("Voted for", labels = c("McCain-Obama", "Obama-Romney"), values=c("blue", "red"))


```



```{r demographic plots of switchers, echo = FALSE}

# Who are these switchers? 

  # Demographics:
    
    # By race (percentages, dodged):

switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(race_12, ..prop.., fill = reorder(presvote12, race_12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..)), position = position_dodge()) + scale_y_continuous(labels = scales::percent) + labs(x = "Race of Switchers", y = "Percentage of Switchers", title = "President 2012 Switchers by Race") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7), label = c("White", "Black", "Hispanic", "Asian", "Native American", "Mixed", "Other")) + theme_classic() + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

      # or (percentages, stacked; all dodged in shiny)

s1 <- switchers %>%
  filter(p12switch == 1) %>%
ggplot(aes(race_12, ..prop.., fill = reorder(presvote12, race_12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Race of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Race") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7), label = c("White", "Black", "Hispanic", "Asian", "Native American", "Mixed", "Other")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Obama-Romney", "McCain-Obama"), values=c("red", "blue"))

    # By sex

s2 <- switchers %>%
  filter(p12switch == 1) %>%
ggplot(aes(gender_12, ..prop.., fill = reorder(presvote12, gender_12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Gender of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Gender") + scale_x_continuous(breaks = c(1, 2), label = c("Male", "Female")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Romney", "Obama"), values=c("red", "blue"))

  # By age

s3 <- switchers %>%
  filter(p12switch == 1) %>%
ggplot(aes(pres.agegroup12, ..prop.., fill = reorder(presvote12, pres.agegroup12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + xlab("Age of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Age") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8), label = c("18-24", "25-34", "35-44", "45-54", "55-64", "65-74", "75-84", "85-94")) + scale_y_continuous(labels = scales::percent) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Romney", "Obama"), values=c("red", "blue"))

    # By education

s4 <- switchers %>%
  filter(p12switch == 1) %>%
ggplot(aes(educ_12, ..prop.., fill = reorder(presvote12, educ_12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Education Level") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Education") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6), label = c("No High School", "High school graduate", "Some college", "2-year", "4-year", "Post-grad")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Romney", "Obama"), values=c("red", "blue")) + coord_flip()

    # By party (dropping NAs means 2 less observations)

s5 <- switchers %>%
  filter(p12switch == 1, partyreg12 < 5) %>%
  ggplot(aes(partyreg12, ..prop.., fill = reorder(presvote12, partyreg12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Party of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Party") + scale_x_continuous(breaks = c(1, 2, 3, 4), label = c("None/Ind/Didn't Say", "Democratic", "Republican", "Other")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("Romney", "Obama"), values=c("red", "blue"))

    # By income

s6 <- switchers %>%
  filter(p12switch == 1) %>%
  ggplot(aes(income.12, ..prop.., fill = reorder(presvote12, income.12)), stat = "count") + geom_bar(aes(y = ..count../sum(..count..))) + scale_y_continuous(labels = scales::percent) + xlab("Income of Switchers") + ylab("Percentage of Switchers") + ggtitle("President 2012 Switchers by Income") + scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6), label = c("0-29,999", "30,000-59,999", "60,000-99,999", "100,000-149,999", "150,000+", "Didn't say/Skipped/Not asked")) + theme(panel.background = element_rect("white"), axis.line.x.bottom = element_line("black"), axis.line.y.left = element_line("black")) + scale_fill_manual("Voted for", labels = c("McCain-Obama", "Obama-Romney"), values=c("blue", "red")) + coord_flip()
```

```{r cleaning data to compare switchers to electorate, include = FALSE}

# Comparing switchers to voters in general
  # Keeping only the variables we want and adding new variables to indicate
# switchers, and make age groups and income groups

CCES_Panel <- CCES_Panel %>%
  subset(select = c(caseid, birthyr_12, birthyr_14, gender_12, gender_14, race_12,
                    race_14, CC10_317, CC12_410a, CC10_412, CC12_412, CC14_412,
                    CC12_302, CC14_302, CC12_303d, CC14_303d, CC12_308a, CC14_308a,
                    CC12_308b, CC14_308b, CC12_315a, CC14_315a, CC12_320, CC14_320,
                    CC12_321, CC14_321, CC12_322_1:CC12_322_6, CC14_322_1:CC14_322_6,
                    CC12_324:CC12_329, CC14_324:CC14_329, CC12_341A, CC14_341A,
                    CC12_341C:CC12_341F, CC14_341C:CC14_341F, CC12_341M, CC14_341M,
                    CC12_350, CC14_350, CC12_367, CC14_367, CC12_387_1, CC12_387_2, CC12_387_3, CC12_387_4, CC12_387_5, CC12_387_6, CC12_387_7, CC12_387_8, CC12_387_9, CC12_387_10, CC12_387_11, CC12_387_12, CC12_387_13,
                    CC14_387_1:CC14_387_13, CC12_418aa, CC14_418aa, CC12_422a:CC12_423bb,
                    CC14_422a:CC14_423bb, pid7_12, pid7_14, pid3_12, pid3_14, ideo5_12,
                    ideo5_14, pew_prayer_12, pew_prayer_14, religpew_12, religpew_14,
                    faminc_10, faminc_12, faminc_14, educ_12, educ_14, StateAbbr_12,
                    StateAbbr_14)) %>%
  rename(hvote10 = CC10_412, hvote12 = CC12_412, hvote14 = CC14_412,
       pvote08 = CC10_317, pvote12 = CC12_410a, partyreg12 = CC12_350) %>%
  mutate(h12switch = if_else(hvote10 < 3 & hvote12 < 3 & hvote10 != hvote12, 1, 0),
         h14switch = if_else(hvote12 < 3 & hvote14 < 3 & hvote12 != hvote14, 1, 0),
         p12switch = if_else(pvote08 < 3 & pvote12 < 3 & pvote08 != pvote12, 1, 0),
         age12 = (2012 - birthyr_12),
         age14 = (2014 - birthyr_14),
         agegroup12 = case_when(age12 >= 18 & age12 <= 24 ~ '1', age12 >= 25 & age12 <= 34 ~ '2',
                                age12 >= 35 & age12 <= 44 ~ '3', age12 >= 45 & age12 <= 54 ~ '4',
                                age12 >= 55 & age12 <= 64 ~ '5', age12 >= 65 & age12 <= 74 ~ '6',
                                age12 >= 75 & age12 <= 84 ~ '7', age12 >= 85 & age12 <= 94 ~ '8'),
         agegroup14 = case_when(age14 >= 18 & age14 <= 24 ~ '1', age14 >= 25 & age14 <= 34 ~ '2',
                                age14 >= 35 & age14 <= 44 ~ '3', age14 >= 45 & age14 <= 54 ~ '4',
                                age14 >= 55 & age14 <= 64 ~ '5', age14 >= 65 & age14 <= 74 ~ '6',
                                age14 >= 75 & age14 <= 84 ~ '7', age14 >= 85 & age14 <= 94 ~ '8'),
         income10 = case_when(faminc_10 >= 1 & faminc_10 <= 3 ~ '1', faminc_10 >= 4 & faminc_10 <= 6 ~ '2',
                              faminc_10 >= 7 & faminc_10 <= 9 ~ '3', faminc_10 >= 10 & faminc_10 <= 11 ~ '4',
                              faminc_10 >= 12 & faminc_10 < 33 ~ '5', faminc_10 >= 32 | is.na(faminc_10) ~ '6'),
         income12 = case_when(faminc_12 >= 1 & faminc_12 <= 3 ~ '1', faminc_12 >= 4 & faminc_12 <= 6 ~ '2',
                              faminc_12 >= 7 & faminc_12 <= 9 ~ '3', faminc_12 >= 10 & faminc_12 <= 11 ~ '4',
                              faminc_12 >= 12 & faminc_12 < 33 ~ '5', faminc_12 >= 32 | is.na(faminc_12) ~ '6'),
         income14 = case_when(faminc_14 >= 1 & faminc_14 <= 3 ~ '1', faminc_14 >= 4 & faminc_14 <= 6 ~ '2',
                              faminc_14 >= 7 & faminc_14 <= 9 ~ '3', faminc_14 >= 10 & faminc_14 <= 11 ~ '4',
                              faminc_14 >= 12 & faminc_14 < 33 ~ '5', faminc_14 >= 32 | is.na(faminc_14) ~ '6'))
```

```{r comparing switchers to electorate w/ demographics, echo = FALSE}

# How Pres 2012 switchers compare to the electorate by
  # race:

CCES_Panel %>%
  group_by(p12switch) %>%
  count(race_12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(race_12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Race", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7, 8), label = c("White", "Black", "Hispanic",
                                                                "Asian", "Native American",
                                                                "Mixed", "Other", "Middle Eastern")) +
  theme_classic() +
  scale_fill_manual(na.translate = F, "Group", labels = c("Electorate", "Switchers"), values=c("dark grey", "purple"))

  # gender:

CCES_Panel %>%
  group_by(p12switch) %>%
  count(gender_12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(gender_12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Gender", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_continuous(breaks = c(1, 2), label = c("Male", "Female")) +
  theme_classic() +
  scale_fill_manual(na.translate = F, "Group", labels = c("Electorate", "Switchers"), values=c("dark grey", "purple"))

  # age:

CCES_Panel %>%
  group_by(p12switch) %>%
  count(agegroup12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(agegroup12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Age", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_discrete(breaks = c(1, 2, 3, 4, 5, 6, 7, 8), label = c("18-24", "25-34", "35-44",
                                                                   "45-54", "55-64", "65-74", "75-84",
                                                                   "85-94")) +
  theme_classic() +
  scale_fill_manual(na.translate = F, "Group", labels = c("Electorate", "Switchers"), values=c("dark grey", "purple"))

  # education:

CCES_Panel %>%
  group_by(p12switch) %>%
  count(educ_12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(educ_12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Education", y = "Percentage of Group", title = "How Switchers Compare to Electorate") +
  scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6), label = c("No High School",
                                                           "High school graduate", "Some college",
                                                           "2-year", "4-year", "Post-grad")) +
  theme_classic() +
  scale_fill_manual(na.translate = F, "Group", labels = c("Electorate", "Switchers"), values=c("dark grey", "purple")) +
  coord_flip()

  # party

CCES_Panel %>%
  filter(partyreg12 < 5) %>%
  group_by(p12switch) %>%
  count(partyreg12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(partyreg12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Party",
       y = "Percentage of Group",
       title = "How Switchers Compare to Electorate") +
  scale_x_continuous(breaks = c(1, 2, 3, 4),
                     label = c("None/Independent/Didn't Say", "Democrat",
                               "Republican", "Other")) +
  theme_classic() +
  scale_fill_manual(na.translate = F,
                    "Group",
                    labels = c("Electorate", "Switchers"),
                    values=c("dark grey", "purple"))

  # income
  
CCES_Panel %>%
  group_by(p12switch) %>%
  count(income12) %>%
  mutate(pct = n/sum(n)) %>%
  ggplot(aes(income12, pct, fill = factor(p12switch))) +
  geom_col(position = position_dodge()) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Income",
       y = "Percentage of Group",
       title = "How Switchers Compare to Electorate") +
  scale_x_discrete(breaks = c(1, 2, 3, 4, 5, 6),
                   label = c("0-29,999", "30,000-59,999","60,000-99,999",
                             "100,000-149,999", "150,000+",
                             "Didn't say/Skipped/Not asked")) +
  theme_classic() +
  scale_fill_manual(na.translate = F,
                    "Group",
                    labels = c("Electorate", "Switchers"),
                    values=c("dark grey", "purple")) +
  coord_flip()
```

```{r prepping for modeling, echo = FALSE}

# regression exploration on race and pres. 2012 switching
  # Making a set dummy variables for race and a new categorical variable for race

CCES_Panel.reg <- CCES_Panel %>%
  dummy_cols(select_columns = c("race_12", "partyreg12", "religpew_12")) %>%
  mutate(race_12_char = case_when(race_12 == 1 ~ "white",
                                  race_12 == 2 ~ "black",
                                  race_12 == 3 ~ "hispanic",
                                  race_12 == 4 ~ "asian",
                                  race_12 == 5 ~ "native american",
                                  race_12 == 6 ~ "mixed",
                                  race_12 == 7 ~ "other",
                                  race_12 == 8 ~ "middle eastern"),
         gender_12 = ifelse(gender_12 == 2, 0, gender_12),
         partyreg12.char = case_when(partyreg12 == 1 ~ "none, ind., didn't say",
                                     partyreg12 == 2 ~ "democrat",
                                     partyreg12 == 3 ~ "republican",
                                     partyreg12 == 4 ~ "other"),
         religpew_12_char = case_when(religpew_12 == 1 ~ "Protestant",
                                      religpew_12 == 2 ~ "Roman Catholic",
                                      religpew_12 == 3 ~ "Mormon",
                                      religpew_12 == 4 ~ "Eastern or Greek Orthodox",
                                      religpew_12 == 5 ~ "Jewish",
                                      religpew_12 == 6 ~ "Muslim",
                                      religpew_12 == 7 ~ "Buddhist",
                                      religpew_12 == 8 ~ "Hindu",
                                      religpew_12 == 9 ~ "Atheist",
                                      religpew_12 == 10 ~ "Agnostic",
                                      religpew_12 == 11 ~ "Nothing in particular",
                                      religpew_12 == 12 ~ "Other"),
         p12switch = ifelse(is.na(p12switch), 0, p12switch))

predict.CCES <- CCES_Panel.reg %>%
  filter(pvote08 < 3) %>%
  mutate(income12 = as.numeric(income12),
         ideo.diff.obama = abs(CC12_341A - CC12_341C),
         ideo.diff.romney = abs(CC12_341A - CC12_341D),
         ideo.diff.dem = abs(CC12_341A - CC12_341E),
         ideo.diff.repub = abs(CC12_341A - CC12_341F),
         region12 = ifelse(StateAbbr_12 %in% state_info$state_abbrev,
                           state_info$region, "NA"))
```

```{r life events, echo = FALSE}

mod.lifeevents <- glm(p12switch ~ CC12_387_1 + CC12_387_2 + CC12_387_3 + CC12_387_4 + CC12_387_5 + CC12_387_6 + CC12_387_7 + CC12_387_8 + CC12_387_9 + CC12_387_10 + CC12_387_11 + CC12_387_12 + CC12_387_13, binomial, data = predict.CCES)

mod.lifeevents %>%
  tidy() %>%
  select(term, estimate, std.error, p.value) %>%
  arrange(p.value)

CCES_Panel$perc.docvisit12 <- 100 * sum(CCES_Panel$CC12_387_1 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.eroom12 <- 100 * sum(CCES_Panel$CC12_387_2 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.raise12 <- 100 * sum(CCES_Panel$CC12_387_3 == 1)/nrow(CCES_Panel)
         
CCES_Panel$perc.lostjob12 <- 100 * sum(CCES_Panel$CC12_387_4 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.cutbenefits12 <- 100 * sum(CCES_Panel$CC12_387_5 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.promotion12 <- 100 * sum(CCES_Panel$CC12_387_6 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.betterjob12 <- 100 * sum(CCES_Panel$CC12_387_7 == 1)/nrow(CCES_Panel)
       
CCES_Panel$perc.trafficticket12 <- 100 * sum(CCES_Panel$CC12_387_8 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.crimevic12 <- 100 * sum(CCES_Panel$CC12_387_9 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.newchild12 <- 100 * sum(CCES_Panel$CC12_387_10 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.moveoutchild12 <- 100 * sum(CCES_Panel$CC12_387_11 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.newmarriage12 <- 100 * sum(CCES_Panel$CC12_387_12 == 1)/nrow(CCES_Panel)

CCES_Panel$perc.newdivorce12 <- 100 * sum(CCES_Panel$CC12_387_13 == 1)/nrow(CCES_Panel)

pres12_vars$perc.docvisit12 <- 100 * sum(pres12_vars$docvisit12 == 1)/nrow(pres12_vars)

pres12_vars$perc.eroom12 <- 100 * sum(pres12_vars$eroom12 == 1)/nrow(pres12_vars)

pres12_vars$perc.raise12 <- 100 * sum(pres12_vars$raise12 == 1)/nrow(pres12_vars)
         
pres12_vars$perc.lostjob12 <- 100 * sum(pres12_vars$lostjob12 == 1)/nrow(pres12_vars)

pres12_vars$perc.cutbenefits12 <- 100 * sum(pres12_vars$cutbenefits12 == 1)/nrow(pres12_vars)

pres12_vars$perc.promotion12 <- 100 * sum(pres12_vars$promotion12 == 1)/nrow(pres12_vars)

pres12_vars$perc.betterjob12 <- 100 * sum(pres12_vars$betterjob12 == 1)/nrow(pres12_vars)
       
pres12_vars$perc.trafficticket12 <- 100 * sum(pres12_vars$trafficticket12 == 1)/nrow(pres12_vars)

pres12_vars$perc.crimevic12 <- 100 * sum(pres12_vars$crimevic12 == 1)/nrow(pres12_vars)

pres12_vars$perc.newchild12 <- 100 * sum(pres12_vars$newchild12 == 1)/nrow(pres12_vars)

pres12_vars$perc.moveoutchild12 <- 100 * sum(pres12_vars$moveoutchild12 == 1)/nrow(pres12_vars)

pres12_vars$perc.newmarriage12 <- 100 * sum(pres12_vars$newmarriage12 == 1)/nrow(pres12_vars)

pres12_vars$perc.newdivorce12 <- 100 * sum(pres12_vars$newdivorce12 == 1)/nrow(pres12_vars)

cces.change.lifeevent <- CCES_Panel %>% select(perc.docvisit12:perc.newdivorce12) %>% slice(1)

pres12switch.change.lifeevent <- pres12_vars %>% select(perc.docvisit12:perc.newdivorce12) %>% slice(1)

cces.long.change <- cces.change.lifeevent %>% pivot_longer(perc.docvisit12:perc.newdivorce12)

pres12.long.change <- pres12switch.change.lifeevent %>% pivot_longer(perc.docvisit12:perc.newdivorce12)

diff.lifeevents <- cces.long.change %>%
  full_join(pres12.long.change, by = 'name') %>%
  mutate(diff = value.x - value.y)

diff.lifeevents %>%
  ggplot(aes(diff, name)) +
  geom_point() +
  labs(title = "How Switchers and the Electorate Differ",
       subtitle = "Experiences within the last 2 years",
       x = "Percentage Point Difference between Electorate and Switchers",
       y = "Life Event") +
  theme_minimal() +
  scale_x_continuous(limits = c(-10, 10)) +
  scale_y_discrete(label = c("Better job", "Been victim of a crime",
                             "Employee benefits cut", "Visited doctor's office",
                             "Visited emergency room", "Loss of job",
                             "Child moved out", "New child in family", "Divorce",
                             "Marriage", "Promotion at work", "Raise at work",
                             "Traffic ticket"))
```


```{r models, echo = FALSE}

mod.all <- glm(p12switch ~  age12 + CC12_302 + CC12_303d + CC12_308a + CC12_320 +
                 CC12_321 + CC12_322_1 + CC12_322_2 + CC12_322_3 + CC12_322_4 +
                 CC12_322_5 + CC12_322_6 + CC12_324 + CC12_325 + CC12_326 + CC12_327 +
                 CC12_328 + CC12_329 + CC12_341A + CC12_341C + CC12_341D + CC12_341E +
                 CC12_341F + CC12_387_1 + CC12_387_2 + CC12_387_3 + CC12_387_4 +
                 CC12_387_5 + CC12_387_6 + CC12_387_7 + CC12_387_8 + CC12_387_9 +
                 CC12_387_10 + CC12_387_11 + CC12_387_12  + CC12_387_13 + CC12_422a +
                 CC12_422b + CC12_423aa + CC12_423bb + educ_12 +  gender_12 + ideo5_12 +
                 income12 + partyreg12.char + pew_prayer_12 + pvote08 +
                 pvote12 + race_12_char + religpew_12_char + ideo.diff.repub +
                 ideo.diff.dem + ideo.diff.romney + ideo.diff.obama, binomial, predict.CCES)

mod.all %>%
  tidy() %>%
  select(term, estimate, std.error, p.value) %>%
  arrange(p.value)

mod.all.check <- mod.all %>%
  augment(type.predict = "response", type.residuals = "response") %>%
  mutate(conf.low = .fitted - 1.96 * .se.fit,
         conf.high = .fitted + 1.96 * .se.fit) %>%
  select(p12switch, .fitted, conf.low, conf.high, .resid) %>%
  mutate(bi.fitted = ifelse(.fitted < 0.5, 0, 1),
         bi.resid = p12switch - bi.fitted,
         true.positive = ifelse(bi.fitted == 1 & p12switch == 1, 1, 0),
         false.positive = ifelse(bi.fitted == 1 & p12switch == 0, 1, 0),
         true.negative = ifelse(bi.fitted == 0 & p12switch == 0, 1, 0),
         false.negative = ifelse(bi.fitted == 0 & p12switch == 1, 1, 0),
         status = case_when(true.positive == 1 ~ "TP",
                            true.negative == 1 ~ "TN",
                            false.positive == 1 ~ "FP",
                            false.negative == 1 ~ "FN"))

mod.bestvars <- glm(p12switch ~ pvote08 + ideo.diff.repub + CC12_321 +
                      CC12_302 + CC12_322_3 + religpew_12_3 + partyreg12_1 +
                      religpew_12_2, binomial, predict.CCES)

mod.bestvars %>%
  tidy(conf.int = TRUE) %>%
  select(term, estimate, conf.low, conf.high, p.value) %>%
  gt() %>%
  fmt_number(columns = 2:4, decimals = 2) %>%
  fmt_number(columns = 5, decimals = 8) %>%
  cols_label(term = "Variable", estimate = "Estimate", conf.low = "Lower Bound",
             conf.high = "Upper Bound", p.value = "P Value") %>%
  tab_header("Effect of 'Best' Variables on Switching",
             subtitle = "Data from 2010-2014 CCES Panel Survey")

mod.bestvars.check <- mod.bestvars %>%
  augment(type.predict = "response", type.residuals = "response") %>%
  mutate(conf.low = .fitted - 1.96 * .se.fit,
         conf.high = .fitted + 1.96 * .se.fit) %>%
  select(p12switch, .fitted, conf.low, conf.high, .resid) %>%
  mutate(bi.fitted = ifelse(.fitted < 0.5, 0, 1),
         bi.resid = p12switch - bi.fitted,
         true.positive = ifelse(bi.fitted == 1 & p12switch == 1, 1, 0),
         false.positive = ifelse(bi.fitted == 1 & p12switch == 0, 1, 0),
         true.negative = ifelse(bi.fitted == 0 & p12switch == 0, 1, 0),
         false.negative = ifelse(bi.fitted == 0 & p12switch == 1, 1, 0),
         status = case_when(true.positive == 1 ~ "TP",
                            true.negative == 1 ~ "TN",
                            false.positive == 1 ~ "FP",
                            false.negative == 1 ~ "FN"))

table(mod.bestvars.check$status)

besvars.accuracy <- 100 - sum(abs(mod.bestvars.check$bi.resid))/nrow(mod.bestvars.check)

bestvars.check.switch <- mod.bestvars.check %>% filter(p12switch == 1)

# The "best" variables model predicts no switching when switching does indeed occur.

mod.bestvars.check %>%
  ggplot(aes(status, .fitted), group = status) +
  labs(title = "Evaluating the Model's Predictions", x = "Prediction Status",
       y = "Probability of Switching") +
  scale_x_discrete(label = c("False Negative", "True Negative", "True Positive")) +
  geom_point() +
  geom_jitter() +
  theme_minimal()
```


